# Generated by Django 3.0.3 on 2020-02-29 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_frame', models.CharField(choices=[('1d', '1 day')], max_length=10)),
                ('chart_type', models.CharField(choices=[('candle', 'Candle')], max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_price', models.DecimalField(decimal_places=10, max_digits=30)),
                ('high_price', models.DecimalField(decimal_places=10, max_digits=30)),
                ('low_price', models.DecimalField(decimal_places=10, max_digits=30)),
                ('close_price', models.DecimalField(decimal_places=10, max_digits=30)),
                ('volume', models.BigIntegerField()),
                ('source', models.CharField(max_length=50)),
                ('candle_date', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chart.Chart')),
            ],
        ),
    ]
