# Generated by Django 3.0.3 on 2020-03-06 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='chart_type',
            field=models.CharField(choices=[('candle', 'Candle'), ('point', 'Point')], max_length=10),
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=10, max_digits=30)),
                ('volume', models.BigIntegerField()),
                ('source', models.CharField(max_length=50)),
                ('point_date', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chart.Chart')),
            ],
        ),
    ]
