# Generated by Django 3.0.3 on 2020-03-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_auto_20200306_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='time_frame',
            field=models.CharField(choices=[('1d', '1 day'), ('1h', '1 hour')], max_length=10),
        ),
        migrations.AlterField(
            model_name='point',
            name='volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
