# Generated by Django 3.0.3 on 2020-03-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0003_auto_20200310_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
