# Generated by Django 3.0.3 on 2020-04-12 03:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0006_auto_20200412_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmilestone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetmilestone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='milestone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
