# Generated by Django 3.0.3 on 2020-04-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0007_auto_20200412_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmilestone',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
