# Generated by Django 3.0.3 on 2020-04-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0008_auto_20200412_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmilestone',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='assetmilestone',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True),
        ),
    ]
