# Generated by Django 3.0.3 on 2020-04-21 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0009_auto_20200419_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetmilestone',
            name='percentage',
        ),
    ]
