# Generated by Django 3.0.3 on 2020-05-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0011_auto_20200429_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetmilestone',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='assetmilestone',
            name='max_price_date',
        ),
        migrations.RemoveField(
            model_name='assetmilestone',
            name='min_price',
        ),
        migrations.RemoveField(
            model_name='assetmilestone',
            name='min_price_date',
        ),
        migrations.AddField(
            model_name='assetmilestone',
            name='biggest_up',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetmilestone',
            name='deepest_down',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetmilestone',
            name='total_performance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
