# Generated by Django 3.0.3 on 2020-05-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0012_auto_20200502_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
