# Generated by Django 3.0.3 on 2020-05-09 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0013_milestone_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='description',
        ),
    ]
