# Generated by Django 3.0.3 on 2020-06-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0015_assetmilestonecomparision'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='milestone_type',
            field=models.CharField(blank=True, choices=[('crisis', 'Crisis'), ('abundance', 'Abundance')], max_length=100, null=True),
        ),
    ]
