sudo: required
language: general

services:
  - docker

after_success:
  - docker build -t mopitz/backend-app -f ./dockers/prod/web/Dockerfile .
  - docker build -t mopitz/backend-nginx -f ./dockers/prod/nginx/Dockerfile .
  - docker build -t mopitz/backend-nginx-proxy -f ./dockers/prod/nginx-proxy/Dockerfile .
  - docker build -t mopitz/backend-caddy -f ./dockers/prod/caddy/Dockerfile .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mopitz/backend-app
  - docker push mopitz/backend-nginx
  - docker push mopitz/backend-nginx-proxy
  - docker push mopitz/backend-caddy

before_deploy:
  - zip -r economicapp-backend.zip Dockerrun.aws.json .ebextensions
  - rm Dockerrun.aws.json
  - rm -R .ebextensions

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: economicapp-backend
  env: EconomicappBackend-env
  bucket_name: elasticbeanstalk-us-east-1-960622128562
  zip-file: economicapp-backend.zip
  skip_cleanup: true
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
