# Generated by Django 3.0.3 on 2020-04-04 05:16

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0008_auto_20200319_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='DilutedEPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=10, max_digits=30)),
                ('time_frames', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('annual', 'Annual'), ('quarterly', 'Quarterly')], max_length=30), blank=True, null=True, size=None)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Asset')),
            ],
        ),
    ]
