# Generated by Django 3.0.3 on 2020-04-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dilutedeps',
            name='diluted_eps_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
