# Generated by Django 3.0.3 on 2020-03-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_asset_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
