# Generated by Django 3.0.3 on 2020-03-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_asset_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='slug',
            field=models.CharField(max_length=256),
        ),
    ]
