# Generated by Django 3.0.3 on 2020-03-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_auto_20200318_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(blank=True, choices=[('cryptos', 'Cryptos'), ('stocks', 'Stocks'), ('commodities', 'Commodities'), ('etf', 'ETF'), ('index', 'Index'), ('futures', 'Futures'), ('currencies', 'Currencies')], max_length=50, null=True),
        ),
    ]
