# Generated by Django 3.0.3 on 2020-05-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0011_asset_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='health',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
