# Generated by Django 3.0.3 on 2020-06-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliooptimization',
            name='total_amount_to_invest',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True),
        ),
    ]
