# Generated by Django 3.0.3 on 2020-06-09 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimization', '0002_portfoliooptimization_total_amount_to_invest'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliooptimization',
            name='optimism',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
